version: "2"

exclude_patterns:
- "src/test/"
- "src/main/java/db/migration/"
- "**/*.js"
- "**/*.css"

plugins:
  checkstyle:
      enabled: true
      config:
        file: ".codeclimate/checkstyle.xml"
  sonar-java:
      enabled: true
      config:
        minimum_severity: critical

engines:
  checkstyle:
      enabled: true
      checks:
          com.puppycrawl.tools.checkstyle.checks.coding.MagicNumberCheck:
          enabled: false