engines:
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck:
        enabled: false

plugins:
  checkstyle:
      enabled: true
      config:
        file: ".codeclimate/checkstyle.xml"