############## Test properties ###################################################################
# This is the default property file which can be used as a template for default configuration.   #
# Copy this file to `/config/application.properties`, with the runnable jar in the `/` directory #
##################################################################################################

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/events
    username: postgres
    password:

  data.jpa.repositories.enabled: true

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop

    properties.hibernate.default_schema: public

  mail:
    host: 127.0.0.1
    port: 1025

  thymeleaf:
    mode: HTML5
    encoding: UTF-8

flyway.enabled: false
server:
    port: 8080
    context-path: /events

wisvch.connect:
  issuerUri: https://connect.ch.tudelft.nl
  clientUri: http://localhost:8080/events

  admin-groups: test
  beta-users: test

wisvch.payments:
    issuerUri: https://ch.tudelft.nl/payments
    clientUri: http://localhost:8080/events

#Spring Boot Actuator endpoint settings
management:
    context-path: /management
    security.roles: ADMIN
    endpoints:
        enabled: false
        health.enabled: true