name: Test and Deploy
on:
  push:
jobs:
  testAndDeploy:
    name: Test and Deploy Docker Image
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_USER: postgres
          POSTGRES_DB: events
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Setup for test report
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Test Coverage
      run: ./gradlew clean build jacocoTestReport jacocoFix --scan
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: quay.io/wisvch/events:sha-40043ad
        tags: type=sha, prefix={{date 'YYYYMMDD'}}-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Quay login
      uses: docker/login-action@v1
      with: 
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Quay
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.ref == 'refs/heads/master' }}
